# Base configuration
markdown: jekyll
highlighter: rouge
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: Kaylah's Website
# Author/Organization info to be displayed in the templates
author:
  name: Kaylah Tan
  url: http://linkedin.com/kaylah-tan

# When using this template with a project (repository) page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
baseurl: http"://kaylah-tan.github.io

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
#logourl: /assets/img/dc_logo.png
#logoalt: The D.C. flag

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home Page
  internal: true
  url: ./
- text: Add a new page
  internal: true
  url: add-a-new-page
- text: About Me
  internal: true
  url: configure-the-guide
- text: My Projects
  internal: true
  url: github
- text: Contact
  glossary: true
- text: Edit this Repo
  internal: false
  url: https://github.com/kaylah-tan
# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: Walla Wineries 
  description: 
  url:https://github.com/kaylah-tan/walla-walla-valley-wineries

google_analytics_ua: 

# Style Variables
brand_color: "#DA253B"
