remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Kaylah Tan's Github Page
description: Let me show you how much Whitman College actually taught me ;)
